spring:
  application:
    name: ticketing-system

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
